name: Continuous Integration
on: [push]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build C# Code
      working-directory: DotnetTemplate.Web
      run: dotnet build
    - name: Run C# Tests
      working-directory: DotnetTemplate.Web.Tests
      run: dotnet test
    - name: Build TypeScript Code
      working-directory: DotnetTemplate.Web
      run: npm install && npm run build 
    - name: Run TypeScript Test
      working-directory: DotnetTemplate.Web
      run: npm t
    - name: Send custom JSON data to Slack workflow
      payload: {"text": "Hello World, I'm a Slack Bot!"}
      env: SLACK_WEBHOOK_URL: ${{ secrets.SLACKBOT }} 
     


